title : Tenly 互联网哲学
tagline: 记录我的千丝智慧
author :
  name : Tenly Wu
  email : tenlywu@gmail.com
  github : tenlywu
  twitter : tenlywu
  feedburner : tenlywu

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
